version: "3.7"

services:
  database:
      image: mysql:latest
      build: ./mysql/
      platform: linux/amd64
      command:
        - "--default-authentication-plugin=mysql_native_password"
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=codetest
        - MYSQL_USER=codetest
        - MYSQL_PASSWORD=swordfish
      ports:
        - "32001:3306"
      restart: always 

  Load-Data:
    image: load_data
    build: ./load_data/
    command: sh -c "python3 ./load_data.py"
    volumes:
      - ./data:/data
    healthcheck:
      test: "exit 0"
    depends_on:
      - database

  Get-Results:
    image: results
    build: ./results/
    command: sh -c "sleep 60s; python3 ./get_results.py"
    volumes:
      - ./data:/data
    depends_on:
      Load-Data:
        condition: service_healthy
    restart: always 

 
